name: coveralls

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Checks if Docker Daemon is running
      run: systemctl status docker

    - name: Generate client and spec and run tests
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: ./gradlew generateApiClient generateApiSpec test